[management]
gitlab01 ansible_host=172.16.10.128 ansible_user=user1 ansible_become_password=123456

[master]
k8s-master ansible_host=172.16.30.129 ansible_user=ubuntu master_ip=172.16.30.129

[worker]
k8s-worker1 ansible_host=172.16.30.130 ansible_user=ubuntu worker_ip=172.16.30.130
k8s-worker2 ansible_host=172.16.30.131 ansible_user=ubuntu worker_ip=172.16.30.131

[harbor]
harbor-server ansible_host=172.16.20.128 ansible_user=user harbor_ip=172.16.20.128

[k8s_cluster:children]
master
worker

[all:vars]
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[database]
db01 ansible_host=192.168.10.40 ansible_user=user1
db02 ansible_host=192.168.10.41 ansible_user=user1

