---
# 노드 IP 
master_ip: 192.168.159.120
worker_ip: 192.168.159.121
worker2_ip: 192.168.159.123
harbor_ip: 192.168.159.122

# Kubernetes 버전 
kubernetes_version: "1.29.0-1.1"
kubernetes_apt_version: "v1.29"

# Calico CNI 
# 호스트 대역과 겹치지 않는 10.244.0.0/16 사용
pod_network_cidr: "10.244.0.0/16"
calico_manifest_url: "https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/calico.yaml"

# Harbor
harbor_version: "v2.10.1"
harbor_hostname: "192.168.159.122"
harbor_admin_password: "Harbor12345"   # 운영 전 반드시 변경
harbor_install_dir: "/opt/harbor"

# containerd 
containerd_version: "1.7.13"

# git Lab URL
gitlab_external_url: "http://10.1.201.127"
