---
- hosts: all
  become: yes

  tasks:

  - name: update package
    apt:
      update_cache: yes


  - name: install tools
    apt:
      name:
        - curl
        - wget
        - vim
        - git
        - net-tools
      state: present