---
- name: Load gitlab variables
  include_vars:
    file: ../../../group_vars/all.yml


- name: Install GitLab dependencies
  apt:
    name:
      - curl
      - openssh-server
      - ca-certificates
      - tzdata
    state: present
    update_cache: yes


- name: Add GitLab repository
  shell: |
    curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.deb.sh | bash


- name: Install GitLab
  apt:
    name: gitlab-ee
    state: present


- name: Configure GitLab external url
  lineinfile:
    path: /etc/gitlab/gitlab.rb
    regexp: "^external_url"
    line: "external_url 'http://10.1.201.127'"
  notify:
    - Reconfigure GitLab
